
import React, { useState, useEffect } from 'react';
import { FileText, Calendar, Eye, Loader2, Search, ArrowRight, Gavel, X, AlertCircle } from 'lucide-react';
import { UserDocument } from '../types';
import { apiRequest } from '../services/apiService';

const MyDocuments: React.FC = () => {
  const [documents, setDocuments] = useState<UserDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedDoc, setSelectedDoc] = useState<UserDocument | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchDocuments();
  }, []);

  const fetchDocuments = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiRequest('/legal/my-documents');
      setDocuments(data);
    } catch (e: any) {
      console.error("Failed to fetch documents", e);
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center space-y-4">
        <Loader2 className="w-10 h-10 text-indigo-600 animate-spin" />
        <p className="text-slate-500 font-bold uppercase tracking-widest text-xs">Retrieving Case Files...</p>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between mb-10">
        <div>
          <h2 className="text-3xl font-bold font-serif text-slate-900">My Document History</h2>
          <p className="text-slate-500 mt-2">Archive of all previous legal analyses generated by LEGALLENS AI.</p>
        </div>
        <div className="bg-indigo-50 px-6 py-3 rounded-2xl flex items-center gap-3">
          <FileText className="w-5 h-5 text-indigo-600" />
          <span className="text-sm font-bold text-indigo-700">{documents.length} Records</span>
        </div>
      </div>

      {error && (
        <div className="mb-10 bg-red-50 border border-red-100 p-6 rounded-[32px] flex items-center gap-4 text-red-700">
          <AlertCircle className="w-6 h-6 shrink-0" />
          <div className="flex-1">
            <p className="font-bold">Offline Sync Error</p>
            <p className="text-sm opacity-80">{error}</p>
          </div>
          <button onClick={fetchDocuments} className="bg-red-700 text-white px-5 py-2 rounded-xl text-xs font-bold">Retry Connection</button>
        </div>
      )}

      {documents.length === 0 && !error ? (
        <div className="bg-white border-2 border-dashed border-slate-200 rounded-[40px] p-20 flex flex-col items-center justify-center text-center space-y-6">
          <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center">
            <Search className="w-10 h-10 text-slate-300" />
          </div>
          <div>
            <h3 className="text-xl font-bold text-slate-900">No records found</h3>
            <p className="text-slate-500 mt-2 max-w-xs mx-auto">Analyze your first legal document to start building your professional archive.</p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {documents.map((doc) => (
            <div 
              key={doc.id}
              className="bg-white p-8 rounded-[32px] border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all group cursor-pointer"
              onClick={() => setSelectedDoc(doc)}
            >
              <div className="bg-indigo-50 w-14 h-14 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-indigo-600 transition-colors">
                <FileText className="w-7 h-7 text-indigo-600 group-hover:text-white" />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2 truncate" title={doc.name}>{doc.name}</h3>
              <div className="flex items-center gap-2 text-slate-400 text-xs font-bold uppercase tracking-widest mb-6">
                <Calendar className="w-3.5 h-3.5" />
                {new Date(doc.uploadDate).toLocaleDateString()}
              </div>
              
              <div className="flex items-center justify-between pt-6 border-t border-slate-50">
                <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-widest">Analysis Ready</span>
                <div className="w-8 h-8 rounded-full bg-slate-50 flex items-center justify-center text-slate-400 group-hover:bg-indigo-600 group-hover:text-white transition-all">
                  <Eye className="w-4 h-4" />
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Modal for analysis view */}
      {selectedDoc && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-[100] flex items-center justify-center p-6 animate-in fade-in duration-300">
          <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-[40px] shadow-2xl overflow-hidden flex flex-col animate-in zoom-in-95 duration-300">
            <div className="bg-slate-900 p-8 flex items-center justify-between shrink-0">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-amber-500 rounded-xl flex items-center justify-center">
                  <Gavel className="w-6 h-6 text-slate-900" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white font-serif">{selectedDoc.name}</h3>
                  <p className="text-slate-400 text-xs font-bold uppercase tracking-widest mt-1">
                    Archived Analysis • {new Date(selectedDoc.uploadDate).toLocaleDateString()}
                  </p>
                </div>
              </div>
              <button 
                onClick={() => setSelectedDoc(null)}
                className="p-3 bg-white/10 hover:bg-white/20 text-white rounded-full transition-colors"
              >
                <X className="w-6 h-6" />
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-12 custom-scrollbar bg-slate-50/50">
              <div className="bg-white p-10 rounded-3xl border border-slate-100 shadow-sm">
                <div className="prose prose-slate max-w-none prose-sm whitespace-pre-wrap leading-relaxed text-slate-700">
                  {selectedDoc.analysis}
                </div>
              </div>
            </div>
            
            <div className="p-8 bg-white border-t border-slate-100 flex items-center justify-between shrink-0">
              <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Verified by Legallens Intelligence System</p>
              <button 
                onClick={() => setSelectedDoc(null)}
                className="bg-slate-900 text-white px-8 py-3 rounded-2xl font-bold text-sm transition-all active:scale-95"
              >
                Close Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MyDocuments;
